# PICoin Stellar TOML

VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="PICoin Project"
ORG_URL="https://picoinproject.org"
ORG_LOGO="https://picoinproject.org/assets/logo.png"
ORG_DESCRIPTION="Model of public access to capital."
ORG_EMAIL="info@picoinproject.org"

[[CURRENCIES]]
code="PIC"
issuer="GCKUEZHJJCSODYFTF32BFMSD7C4IYY73FECHCL5B72SFHPMSDVG6S7D2"

display_decimals=7

name="PICoin"
desc="Pension Investing Coin"

image="https://picoinproject.org/assets/picoin_toml_512.png"

fixed_number=750000000000
max_number=750000000000

status="live"

[[ACCOUNTS]]
public_key="GD5WRB66PMR2DNEA3V33FCVT4REHDQ3WVUYSZAEOYCLY64VPUIINKZGX"
desc="PICoin ICO wallet"
